upstream wave_network {
  least_conn; # Distribute loaded to least busy bot instance
  # Expecting 3 PM2 or Docker instances running on different ports
  server 127.0.0.1:8989;
  server 127.0.0.1:8990;
  server 127.0.0.1:8991;
  keepalive 32;
}

server {
  listen 80;
  server_name api.yourdomain.com;

  location / {
    proxy_pass http://wave_network;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
    
    # Real IP passing
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  # Dashboard Web Socket endpoint (long-polling/ws)
  location /socket.io/ {
    proxy_pass http://wave_network;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header Host $host;
  }
}
